# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  config.vm.box = "trusty64"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
 
  config.vm.define "trustybox" do |trustybox|
    trustybox.vm.host_name = "trustybox"
    trustybox.vm.network "private_network", ip: "192.168.60.11"
    trustybox.vm.network "private_network", ip: "192.168.40.10"
  end
        
end
